"""presupuesto por usuario

Revision ID: 68e5981a4250
Revises: 08a6996e8e55
Create Date: 2026-09-18 15:03:17.834644
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '68e5981a4250'
down_revision: Union[str, None] = '08a6996e8e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_budgets',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tokens_limit', sa.Integer(), nullable=False),
    sa.Column('tokens_reserved', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tokens_used', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('tokens_reserved >= 0', name='ck_budget_reserved_positive'),
    sa.CheckConstraint('tokens_used >= 0', name='ck_budget_used_positive'),
    sa.PrimaryKeyConstraint('user_id', 'window_start')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_budgets')
    # ### end Alembic commands ###
