"""task_id en pending_approvals

Revision ID: 08a6996e8e55
Revises: e442bff6ab7c
Create Date: 2026-09-18 14:51:23.244097
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '08a6996e8e55'
down_revision: Union[str, None] = 'e442bff6ab7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_approvals', sa.Column('task_id', sa.String(length=40), nullable=True))
    op.create_foreign_key(None, 'pending_approvals', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'pending_approvals', type_='foreignkey')
    op.drop_column('pending_approvals', 'task_id')
    # ### end Alembic commands ###
