"""tabla tool_executions

Revision ID: 043185fe37d4
Revises: 394a006de4b0
Create Date: 2026-09-18 13:33:42.100196
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '043185fe37d4'
down_revision: Union[str, None] = '394a006de4b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_executions',
    sa.Column('tool_use_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=40), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('in_flight', 'done', name='toolexecutionstatus', native_enum=False), server_default='in_flight', nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tool_use_id')
    )
    op.create_index('ix_tool_exec_conversation', 'tool_executions', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tool_exec_conversation', table_name='tool_executions')
    op.drop_table('tool_executions')
    # ### end Alembic commands ###
