"""task_id en execution_steps

Revision ID: 12ace09b5e58
Revises: 043185fe37d4
Create Date: 2026-09-18 13:55:46.298772
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '12ace09b5e58'
down_revision: Union[str, None] = '043185fe37d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution_steps', sa.Column('task_id', sa.String(length=40), nullable=True))
    op.create_index('ix_steps_task_id', 'execution_steps', ['task_id', 'id'], unique=False)
    op.create_foreign_key(None, 'execution_steps', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'execution_steps', type_='foreignkey')
    op.drop_index('ix_steps_task_id', table_name='execution_steps')
    op.drop_column('execution_steps', 'task_id')
    # ### end Alembic commands ###
