"""cancelacion de tareas

Revision ID: 21a0620ffa59
Revises: 12ace09b5e58
Create Date: 2026-09-18 14:16:12.771860
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '21a0620ffa59'
down_revision: Union[str, None] = '12ace09b5e58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('cancel_requested', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'cancel_requested')
    # ### end Alembic commands ###
