"""columna retries en tasks

Revision ID: 394a006de4b0
Revises: 5060b07b8919
Create Date: 2026-09-16 16:57:08.266827
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '394a006de4b0'
down_revision: Union[str, None] = '5060b07b8919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('retries', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'retries')
    # ### end Alembic commands ###
