"""estado pending_approval en tasks

Revision ID: 5060b07b8919
Revises: ff6a3478616d
Create Date: 2026-09-16 15:20:38.087732
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5060b07b8919'
down_revision: Union[str, None] = 'ff6a3478616d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('pending', 'running', 'success', 'failed', 'pending_approval', name='taskstatus', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('pending', 'running', 'success', 'failed', 'pending_approval', name='taskstatus', native_enum=False),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    # ### end Alembic commands ###
