"""heartbeat en tasks

Revision ID: e442bff6ab7c
Revises: 21a0620ffa59
Create Date: 2026-09-18 14:28:56.158512
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e442bff6ab7c'
down_revision: Union[str, None] = '21a0620ffa59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'heartbeat_at')
    # ### end Alembic commands ###
