"""Read-only order tools. Every query is scoped to the authenticated customer."""

from langchain.tools import ToolRuntime, tool

from app.core.context import AgentContext
from app.tools.serialize import to_json


# parse_docstring=True: the summary becomes the tool description and each
# `Args:` entry becomes that parameter's description in the JSON schema.
# The docstring is a prompt — the model reads it to decide when to call.
@tool(parse_docstring=True)
async def order_status(order_id: str, runtime: ToolRuntime[AgentContext]) -> str:
    """Look up one of the customer's orders by its id.

    Returns status, category, total, tracking code and dates. Call it before
    saying anything about a specific order; never guess an order's state.

    Args:
        order_id: The order id as the customer wrote it, e.g. "A17".
    """
    # `runtime` is injected by the agent, not generated by the model: it's
    # stripped from the schema the model sees (see app.inspect_tools).
    ctx = runtime.context

    async with ctx.pool.connection() as conn:
        cur = await conn.execute(
            """
            SELECT id, status, category, total, tracking_code,
                   created_at, delivered_at
            FROM orders
            -- customer_id comes from context, so another customer's order is
            -- simply not found. The model can't widen the scope by asking.
            WHERE id = %s AND customer_id = %s
            """,
            # Normalize: the model may pass "a17" or " A17 ".
            (order_id.strip().upper(), ctx.customer_id),
        )
        row = await cur.fetchone()

    if row is None:
        # "Not found" for both "doesn't exist" and "not yours": telling them
        # apart would leak which order ids exist.
        return to_json({"error": "order_not_found", "order_id": order_id})
    return to_json(row)


# parse_docstring here too, even with no Args: without it the raw __doc__ is
# sent verbatim, source indentation included ("\n\n    Use it when…").
@tool(parse_docstring=True)
async def list_my_orders(runtime: ToolRuntime[AgentContext]) -> str:
    """List the customer's orders, most recent first, with status and total.

    Use it when the customer doesn't give an order id, or asks about their
    orders in general.
    """
    # No model-facing arguments at all: the schema the model sees is empty.
    # "Whose orders" is answered by the context, never by the conversation.
    ctx = runtime.context

    async with ctx.pool.connection() as conn:
        cur = await conn.execute(
            """
            SELECT id, status, category, total, created_at
            FROM orders
            WHERE customer_id = %s
            ORDER BY created_at DESC
            LIMIT 20  -- bound what goes into the context window
            """,
            (ctx.customer_id,),
        )
        rows = await cur.fetchall()

    return to_json({"customer_id": ctx.customer_id, "orders": rows})


TOOLS = [order_status, list_my_orders]
